# Generated by Django 4.1.1 on 2023-12-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.CharField(default=0.0002824659275474896, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default=8.027777777777777, max_length=100),
            preserve_default=False,
        ),
    ]
